[2024-12-16T10:58:23.383+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-16T10:58:23.407+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_company_info_to_dwh.Staging_to_Datawarehouse manual__2024-12-16T10:54:59.077631+00:00 [queued]>
[2024-12-16T10:58:23.419+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_company_info_to_dwh.Staging_to_Datawarehouse manual__2024-12-16T10:54:59.077631+00:00 [queued]>
[2024-12-16T10:58:23.419+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-16T10:58:23.439+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): Staging_to_Datawarehouse> on 2024-12-16 10:54:59.077631+00:00
[2024-12-16T10:58:23.451+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5237) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-16T10:58:23.452+0000] {standard_task_runner.py:72} INFO - Started process 5245 to run task
[2024-12-16T10:58:23.451+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'load_company_info_to_dwh', 'Staging_to_Datawarehouse', 'manual__2024-12-16T10:54:59.077631+00:00', '--job-id', '418', '--raw', '--subdir', 'DAGS_FOLDER/company_info_etl.py', '--cfg-path', '/tmp/tmpqu78wbmm']
[2024-12-16T10:58:23.454+0000] {standard_task_runner.py:105} INFO - Job 418: Subtask Staging_to_Datawarehouse
[2024-12-16T10:58:23.536+0000] {task_command.py:467} INFO - Running <TaskInstance: load_company_info_to_dwh.Staging_to_Datawarehouse manual__2024-12-16T10:54:59.077631+00:00 [running]> on host 8e02006e0a25
[2024-12-16T10:58:23.876+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflowDWH' AIRFLOW_CTX_DAG_ID='load_company_info_to_dwh' AIRFLOW_CTX_TASK_ID='Staging_to_Datawarehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T10:54:59.077631+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-16T10:54:59.077631+00:00'
[2024-12-16T10:58:23.877+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-16T10:58:23.923+0000] {base.py:84} INFO - Retrieving connection 'load_to_staging'
[2024-12-16T10:58:24.024+0000] {base.py:84} INFO - Retrieving connection 'load_to_dwh'
[2024-12-16T10:58:24.061+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Tasks/transform_and_load_data/transform_and_load.py", line 59, in hosocongty_transform_and_load
    dwh_cursor.execute(update_sql, (*row, row[1]))  # row[1] là Ma_SIC để cập nhật
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
[2024-12-16T10:58:24.100+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=load_company_info_to_dwh, task_id=Staging_to_Datawarehouse, run_id=manual__2024-12-16T10:54:59.077631+00:00, execution_date=20241216T105459, start_date=20241216T105823, end_date=20241216T105824
[2024-12-16T10:58:24.169+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-16T10:58:24.170+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 418 for task Staging_to_Datawarehouse (not all arguments converted during string formatting; 5245)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Tasks/transform_and_load_data/transform_and_load.py", line 59, in hosocongty_transform_and_load
    dwh_cursor.execute(update_sql, (*row, row[1]))  # row[1] là Ma_SIC để cập nhật
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting
[2024-12-16T10:58:24.191+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-16T10:58:24.230+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-16T10:58:24.233+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
