[2024-12-09T10:18:47.676+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T10:18:47.747+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parallel_historycal_financial_reports.financial_reports.run_main_report_1 manual__2024-12-09T10:18:40.683421+00:00 [queued]>
[2024-12-09T10:18:47.768+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parallel_historycal_financial_reports.financial_reports.run_main_report_1 manual__2024-12-09T10:18:40.683421+00:00 [queued]>
[2024-12-09T10:18:47.768+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-09T10:18:47.802+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): financial_reports.run_main_report_1> on 2024-12-09 10:18:40.683421+00:00
[2024-12-09T10:18:47.838+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1141) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-09T10:18:47.834+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_historycal_financial_reports', 'financial_reports.run_main_report_1', 'manual__2024-12-09T10:18:40.683421+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/Extract_history_financial_data.py', '--cfg-path', '/tmp/tmp5wkfakyv']
[2024-12-09T10:18:47.841+0000] {standard_task_runner.py:105} INFO - Job 208: Subtask financial_reports.run_main_report_1
[2024-12-09T10:18:47.841+0000] {standard_task_runner.py:72} INFO - Started process 1145 to run task
[2024-12-09T10:18:48.125+0000] {task_command.py:467} INFO - Running <TaskInstance: parallel_historycal_financial_reports.financial_reports.run_main_report_1 manual__2024-12-09T10:18:40.683421+00:00 [running]> on host 1ce88e57b286
[2024-12-09T10:18:48.455+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflowDWH' AIRFLOW_CTX_DAG_ID='parallel_historycal_financial_reports' AIRFLOW_CTX_TASK_ID='financial_reports.run_main_report_1' AIRFLOW_CTX_EXECUTION_DATE='2024-12-09T10:18:40.683421+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-09T10:18:40.683421+00:00'
[2024-12-09T10:18:48.457+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-09T10:23:23.906+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Tasks/HistoricalData/company_financial_1.py", line 26, in main_report_1
    select_option_Xpath(driver, "(//div[contains(@class,'list-filter')]//button)[1]")
  File "/opt/ScrapingPackage/navigation.py", line 14, in select_option_Xpath
    option = WebDriverWait(driver, 60).until(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 86, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/expected_conditions.py", line 355, in _predicate
    target = visibility_of(target)(driver)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/expected_conditions.py", line 168, in _predicate
    return _element_if_visible(element)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/expected_conditions.py", line 174, in _element_if_visible
    return element if element.is_displayed() == visibility else False
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 251, in is_displayed
    return self.parent.execute_script(f"/* isDisplayed */return ({isDisplayed_js}).apply(null, arguments);", self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 404, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: chrome=131.0.6778.85); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x55bca7c9431a <unknown>
#1 0x55bca77aa6e0 <unknown>
#2 0x55bca77bbfbb <unknown>
#3 0x55bca77bad45 <unknown>
#4 0x55bca77b0d39 <unknown>
#5 0x55bca77b0e65 <unknown>
#6 0x55bca77af0a0 <unknown>
#7 0x55bca77b2c3e <unknown>
#8 0x55bca783cf6c <unknown>
#9 0x55bca781d462 <unknown>
#10 0x55bca783bed7 <unknown>
#11 0x55bca781d203 <unknown>
#12 0x55bca77ebcc0 <unknown>
#13 0x55bca77ecc9e <unknown>
#14 0x55bca7c61d0b <unknown>
#15 0x55bca7c65c92 <unknown>
#16 0x55bca7c4eb3c <unknown>
#17 0x55bca7c66807 <unknown>
#18 0x55bca7c340df <unknown>
#19 0x55bca7c83578 <unknown>
#20 0x55bca7c83740 <unknown>
#21 0x55bca7c93196 <unknown>
#22 0x7f03bcd49a94 <unknown>
#23 0x7f03bcdd6c3c <unknown>

[2024-12-09T10:23:24.197+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=parallel_historycal_financial_reports, task_id=financial_reports.run_main_report_1, run_id=manual__2024-12-09T10:18:40.683421+00:00, execution_date=20241209T101840, start_date=20241209T101847, end_date=20241209T102324
[2024-12-09T10:23:24.437+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-09T10:23:24.445+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 208 for task financial_reports.run_main_report_1 (Message: stale element reference: stale element not found
  (Session info: chrome=131.0.6778.85); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x55bca7c9431a <unknown>
#1 0x55bca77aa6e0 <unknown>
#2 0x55bca77bbfbb <unknown>
#3 0x55bca77bad45 <unknown>
#4 0x55bca77b0d39 <unknown>
#5 0x55bca77b0e65 <unknown>
#6 0x55bca77af0a0 <unknown>
#7 0x55bca77b2c3e <unknown>
#8 0x55bca783cf6c <unknown>
#9 0x55bca781d462 <unknown>
#10 0x55bca783bed7 <unknown>
#11 0x55bca781d203 <unknown>
#12 0x55bca77ebcc0 <unknown>
#13 0x55bca77ecc9e <unknown>
#14 0x55bca7c61d0b <unknown>
#15 0x55bca7c65c92 <unknown>
#16 0x55bca7c4eb3c <unknown>
#17 0x55bca7c66807 <unknown>
#18 0x55bca7c340df <unknown>
#19 0x55bca7c83578 <unknown>
#20 0x55bca7c83740 <unknown>
#21 0x55bca7c93196 <unknown>
#22 0x7f03bcd49a94 <unknown>
#23 0x7f03bcdd6c3c <unknown>
; 1145)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Tasks/HistoricalData/company_financial_1.py", line 26, in main_report_1
    select_option_Xpath(driver, "(//div[contains(@class,'list-filter')]//button)[1]")
  File "/opt/ScrapingPackage/navigation.py", line 14, in select_option_Xpath
    option = WebDriverWait(driver, 60).until(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 86, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/expected_conditions.py", line 355, in _predicate
    target = visibility_of(target)(driver)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/expected_conditions.py", line 168, in _predicate
    return _element_if_visible(element)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/expected_conditions.py", line 174, in _element_if_visible
    return element if element.is_displayed() == visibility else False
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 251, in is_displayed
    return self.parent.execute_script(f"/* isDisplayed */return ({isDisplayed_js}).apply(null, arguments);", self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 404, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: chrome=131.0.6778.85); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x55bca7c9431a <unknown>
#1 0x55bca77aa6e0 <unknown>
#2 0x55bca77bbfbb <unknown>
#3 0x55bca77bad45 <unknown>
#4 0x55bca77b0d39 <unknown>
#5 0x55bca77b0e65 <unknown>
#6 0x55bca77af0a0 <unknown>
#7 0x55bca77b2c3e <unknown>
#8 0x55bca783cf6c <unknown>
#9 0x55bca781d462 <unknown>
#10 0x55bca783bed7 <unknown>
#11 0x55bca781d203 <unknown>
#12 0x55bca77ebcc0 <unknown>
#13 0x55bca77ecc9e <unknown>
#14 0x55bca7c61d0b <unknown>
#15 0x55bca7c65c92 <unknown>
#16 0x55bca7c4eb3c <unknown>
#17 0x55bca7c66807 <unknown>
#18 0x55bca7c340df <unknown>
#19 0x55bca7c83578 <unknown>
#20 0x55bca7c83740 <unknown>
#21 0x55bca7c93196 <unknown>
#22 0x7f03bcd49a94 <unknown>
#23 0x7f03bcdd6c3c <unknown>

[2024-12-09T10:23:24.493+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-09T10:23:24.653+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-09T10:23:24.688+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
