[2024-12-07T07:02:54.369+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-07T07:02:54.404+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parallel_financial_reports.financial_reports.run_main_report_1 manual__2024-12-07T07:02:50.953756+00:00 [queued]>
[2024-12-07T07:02:54.418+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parallel_financial_reports.financial_reports.run_main_report_1 manual__2024-12-07T07:02:50.953756+00:00 [queued]>
[2024-12-07T07:02:54.418+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-07T07:02:54.438+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): financial_reports.run_main_report_1> on 2024-12-07 07:02:50.953756+00:00
[2024-12-07T07:02:54.452+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_financial_reports', 'financial_reports.run_main_report_1', 'manual__2024-12-07T07:02:50.953756+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/Extract_history_data.py', '--cfg-path', '/tmp/tmpc5klousm']
[2024-12-07T07:02:54.458+0000] {standard_task_runner.py:105} INFO - Job 33: Subtask financial_reports.run_main_report_1
[2024-12-07T07:02:54.458+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=782) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-07T07:02:54.459+0000] {standard_task_runner.py:72} INFO - Started process 789 to run task
[2024-12-07T07:02:54.636+0000] {task_command.py:467} INFO - Running <TaskInstance: parallel_financial_reports.financial_reports.run_main_report_1 manual__2024-12-07T07:02:50.953756+00:00 [running]> on host e645099c8412
[2024-12-07T07:02:55.038+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflowDWH' AIRFLOW_CTX_DAG_ID='parallel_financial_reports' AIRFLOW_CTX_TASK_ID='financial_reports.run_main_report_1' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T07:02:50.953756+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-07T07:02:50.953756+00:00'
[2024-12-07T07:02:55.046+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-07T07:03:43.253+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Tasks/HistoricalData/company_financial_1.py", line 35, in main_report_1
    enter_stock_code(driver, stock_code)
  File "/opt/ScrapingPackage/scraper.py", line 49, in enter_stock_code
    WebDriverWait(driver, 10).until(
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

[2024-12-07T07:03:43.373+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=parallel_financial_reports, task_id=financial_reports.run_main_report_1, run_id=manual__2024-12-07T07:02:50.953756+00:00, execution_date=20241207T070250, start_date=20241207T070254, end_date=20241207T070343
[2024-12-07T07:03:43.451+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-07T07:03:43.454+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 33 for task financial_reports.run_main_report_1 (Message: 
; 789)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Tasks/HistoricalData/company_financial_1.py", line 35, in main_report_1
    enter_stock_code(driver, stock_code)
  File "/opt/ScrapingPackage/scraper.py", line 49, in enter_stock_code
    WebDriverWait(driver, 10).until(
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

[2024-12-07T07:03:43.517+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-07T07:03:43.640+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-07T07:03:43.651+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
