[2024-12-09T10:10:15.480+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T10:10:15.525+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parallel_historycal_financial_reports.financial_reports.run_main_report manual__2024-12-09T10:10:10.211282+00:00 [queued]>
[2024-12-09T10:10:15.544+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parallel_historycal_financial_reports.financial_reports.run_main_report manual__2024-12-09T10:10:10.211282+00:00 [queued]>
[2024-12-09T10:10:15.545+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-09T10:10:15.568+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): financial_reports.run_main_report> on 2024-12-09 10:10:10.211282+00:00
[2024-12-09T10:10:15.582+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=753) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-09T10:10:15.584+0000] {standard_task_runner.py:72} INFO - Started process 759 to run task
[2024-12-09T10:10:15.587+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_historycal_financial_reports', 'financial_reports.run_main_report', 'manual__2024-12-09T10:10:10.211282+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/Extract_history_financial_data.py', '--cfg-path', '/tmp/tmpuqklit2g']
[2024-12-09T10:10:15.590+0000] {standard_task_runner.py:105} INFO - Job 206: Subtask financial_reports.run_main_report
[2024-12-09T10:10:15.781+0000] {task_command.py:467} INFO - Running <TaskInstance: parallel_historycal_financial_reports.financial_reports.run_main_report manual__2024-12-09T10:10:10.211282+00:00 [running]> on host 1ce88e57b286
[2024-12-09T10:10:16.097+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflowDWH' AIRFLOW_CTX_DAG_ID='parallel_historycal_financial_reports' AIRFLOW_CTX_TASK_ID='financial_reports.run_main_report' AIRFLOW_CTX_EXECUTION_DATE='2024-12-09T10:10:10.211282+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-09T10:10:10.211282+00:00'
[2024-12-09T10:10:16.101+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-09T10:13:01.727+0000] {logging_mixin.py:190} INFO - Dữ liệu Kết Quả Kinh Doanh cho mã AGG thiếu từ các năm: 2017.
[2024-12-09T10:13:16.397+0000] {logging_mixin.py:190} INFO - Dữ liệu Lưu Chuyển Tiền Tệ cho mã AGG thiếu từ các năm: 2017.
[2024-12-09T10:13:48.826+0000] {logging_mixin.py:190} INFO - Dữ liệu Cân Đối Kế Toán cho mã AGG thiếu từ các năm: 2017.
[2024-12-09T10:13:48.827+0000] {logging_mixin.py:190} INFO - Mã AGG đã được xử lý
[2024-12-09T10:14:40.356+0000] {logging_mixin.py:190} INFO - Lỗi khi crawl dữ liệu 'Lưu Chuyển Tiền Tệ' cho mã LEC: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=131.0.6778.85); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x55d38b9da31a <unknown>
#1 0x55d38b4f06e0 <unknown>
#2 0x55d38b4f64a3 <unknown>
#3 0x55d38b4f8968 <unknown>
#4 0x55d38b4f89f3 <unknown>
#5 0x55d38b539ba2 <unknown>
#6 0x55d38b563462 <unknown>
#7 0x55d38b533a18 <unknown>
#8 0x55d38b56362e <unknown>
#9 0x55d38b581ed7 <unknown>
#10 0x55d38b563203 <unknown>
#11 0x55d38b531cc0 <unknown>
#12 0x55d38b532c9e <unknown>
#13 0x55d38b9a7d0b <unknown>
#14 0x55d38b9abc92 <unknown>
#15 0x55d38b994b3c <unknown>
#16 0x55d38b9ac807 <unknown>
#17 0x55d38b97a0df <unknown>
#18 0x55d38b9c9578 <unknown>
#19 0x55d38b9c9740 <unknown>
#20 0x55d38b9d9196 <unknown>
#21 0x7f01f8f63a94 <unknown>
#22 0x7f01f8ff0c3c <unknown>
[2024-12-09T10:15:31.399+0000] {logging_mixin.py:190} INFO - Mã LEC đã được xử lý
[2024-12-09T10:17:42.569+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-12-09T10:17:42.718+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-09T10:17:42.728+0000] {process_utils.py:132} INFO - Sending 15 to group 759. PIDs of all processes in the group: [759]
[2024-12-09T10:17:42.730+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 759
[2024-12-09T10:17:42.735+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-09T10:17:43.149+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-09T10:17:43.226+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=759, status='terminated', exitcode=0, started='10:10:14') (759) terminated with exit code 0
